// test-projects/vue-error-test/src/components/ErrorComponents.vue
<template>
  <div class="error-components">
    <h2>Vue Error Test Components</h2>
    
    <!-- Template errors -->
    <div>
      <!-- Error: Property does not exist on this -->
      {{ nonExistentProperty }}
      
      <!-- Error: Cannot read properties of undefined -->
      {{ user.profile.name }}
      
      <!-- Error: Invalid directive -->
      <button v-invalid-directive="handleClick">Invalid Directive</button>
      
      <!-- Error: Method not found -->
      <button @click="nonExistentMethod">Missing Method</button>
    </div>
    
    <div>
      <!-- Error: v-for without key -->
      <div v-for="item in items">{{ item }}</div>
      
      <!-- Error: Invalid v-model -->
      <input v-model="invalidModel.deep.prop" />
    </div>
    
    <button @click="triggerRuntimeError">Trigger Runtime Error</button>
    <button @click="triggerAsyncError">Trigger Async Error</button>
    <button @click="triggerTypeError">Trigger Type Error</button>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted, watch } from 'vue'

// TypeScript errors
interface User {
  name: string;
  age: number;
}

// Error: Type 'string' is not assignable to type 'number'
const invalidUser: User = {
  name: "John",
  age: "thirty" as any
};

// Error: Property 'invalidProp' does not exist on type 'User'
const userWithError = reactive<User>({
  name: "Jane",
  age: 25,
  invalidProp: "error" as any
});

// Runtime error variables
const items = ref([1, 2, 3]);
const user = ref<User | null>(null);
const errorData = ref(null);

// Error: Computed property referencing undefined
const computedError = computed(() => {
  return (undefinedVariable as any).someProperty;
});

// Error: Watch with missing dependencies
watch(() => userWithError.name, (newVal) => {
  console.log(items.value.length); // items not in watch deps
});

// Methods with errors
const triggerRuntimeError = () => {
  try {
    // Error: Cannot read properties of null
    console.log((null as any).someProperty);
    
    // Error: TypeError accessing undefined
    const undefinedObj = undefined;
    console.log((undefinedObj as any).prop);
    
    // Error: ReferenceError
    console.log((window as any).undefinedGlobal);
    
  } catch (error) {
    console.error('Runtime error caught:', error);
  }
};

const triggerAsyncError = async () => {
  try {
    // Error: Network request to invalid URL
    const response = await fetch('https://invalid-api-endpoint.nonexistent');
    const data = await response.json();
    console.log(data);
  } catch (error) {
    console.error('Async error:', error);
    throw new Error('Custom Vue async error');
  }
};

const triggerTypeError = () => {
  // Error: Type assertions causing runtime errors
  const stringVar = "hello";
  const numberResult = (stringVar as any) / 2;
  console.log(numberResult); // NaN
  
  // Error: Calling non-function
  const notAFunction = "string";
  try {
    (notAFunction as any)();
  } catch (error) {
    console.error('Type error:', error);
  }
};

// Lifecycle hook with errors
onMounted(() => {
  // Error: Accessing properties before data is loaded
  console.log(user.value.name); // user is null
  
  // Error: Promise rejection
  Promise.reject(new Error('Vue component mount error'));
  
  // Error: Unhandled promise
  new Promise((resolve, reject) => {
    reject(new Error('Unhandled Vue promise rejection'));
  });
});

// Error: Invalid reactive assignment
// const invalidReactive = reactive("string"); // Should be object

// Error: Ref type mismatch
const typedRef = ref<number>(0);
// typedRef.value = "string"; // Would cause TypeScript error
</script>

<style scoped>
.error-components {
  padding: 20px;
  border: 1px solid #ccc;
  margin: 10px;
}

/* CSS error */
.invalid-css {
  invalid-property: invalid-value;
  color: #invalid-color;
}
</style>

// test-projects/react-error-test/src/ErrorComponents.tsx
import React, { useState, useEffect } from 'react';

// Component with TypeScript errors
export const TypeScriptErrorComponent: React.FC = () => {
  // Error: Type 'string' is not assignable to type 'number'
  const [count, setCount] = useState<number>("invalid");
  
  // Error: Property 'nonExistent' does not exist on type '{}'
  const badObject = {};
  console.log(badObject.nonExistent);
  
  // Error: JSX element implicitly has type 'any'
  const BadJSXElement = () => <div>{unknownVariable}</div>;
  
  return <div>TypeScript Error Component</div>;
};

// Component with runtime errors
export const RuntimeErrorComponent: React.FC = () => {
  const [data, setData] = useState(null);
  
  useEffect(() => {
    // Error: Cannot read properties of null
    setData(null);
    console.log(data.someProperty);
    
    // Error: TypeError: Cannot read properties of undefined
    const undefinedObj = undefined;
    console.log(undefinedObj.prop);
    
    // Error: ReferenceError: undefinedVariable is not defined
    console.log(undefinedVariable);
    
    // Error: fetch request to invalid URL
    fetch('invalid-url').catch(error => {
      console.error('Fetch error:', error);
    });
  }, []);
  
  return <div>Runtime Error Component</div>;
};

// Component with async errors
export const AsyncErrorComponent: React.FC = () => {
  const [loading, setLoading] = useState(false);
  
  const handleAsyncError = async () => {
    setLoading(true);
    try {
      // Error: Network request failure
      const response = await fetch('https://invalid-api-endpoint.nonexistent');
      const data = await response.json();
      console.log(data);
    } catch (error) {
      console.error('Async operation failed:', error);
      throw new Error('Custom async error message');
    } finally {
      setLoading(false);
    }
  };
  
  // Error: Unhandled promise rejection
  const unhandledPromise = () => {
    Promise.reject(new Error('Unhandled promise rejection'));
  };
  
  return (
    <div>
      <button onClick={handleAsyncError}>Trigger Async Error</button>
      <button onClick={unhandledPromise}>Trigger Unhandled Promise</button>
    </div>
  );
};

// Component with JSX errors
export const JSXErrorComponent: React.FC = () => {
  const items = [1, 2, 3];
  
  return (
    <div>
      {/* Error: Missing key prop */}
      {items.map(item => <div>{item}</div>)}
      
      {/* Error: Adjacent JSX elements must be wrapped */}
      <span>First</span>
      <span>Second</span>
      
      {/* Error: Objects are not valid as React children */}
      {items}
      
      {/* Error: Functions are not valid as React children */}
      {() => "function as child"}
    </div>
  );
};

// Component with hook errors
export const HookErrorComponent: React.FC = () => {
  const [count, setCount] = useState(0);
  
  // Error: React Hook useEffect is called conditionally
  if (count > 5) {
    useEffect(() => {
      console.log('Conditional effect');
    }, []);
  }
  
  // Error: React Hook has a missing dependency
  useEffect(() => {
    console.log(count);
  }, []); // count is missing from dependency array
  
  return <div>Hook Error Component</div>;
};

// Component with build/compilation errors
export const BuildErrorComponent: React.FC = () => {
  // Error: Cannot find module
  import invalidModule from 'non-existent-module';
  
  // Error: Syntax error
  const invalidSyntax = {
    prop1: "value1"
    prop2: "value2" // Missing comma
  };
  
  // Error: Type error
  const numberVar: number = "string value";
  
  return <div>Build Error Component</div>;
};
